# sqllite3
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3

# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   <<: *default
#   database: storage/production.sqlite3

# mysql
default: &default
  adapter: mysql2
  encoding: utf8
  host: <%=ENV['MYSQL_HOST']%>
  port: <%=ENV['MYSQL_PORT']%>
  database: <%=ENV['MYSQL_DATABASE']%>
  username: <%=ENV['MYSQL_USERNAME']%>
  password: <%=ENV['MYSQL_PASSWORD']%>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default