# sqllite3
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3

# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   <<: *default
#   database: storage/production.sqlite3

# mysql
default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  database: rails_learn_journey
  port: 3306
  username: root
  password: 

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: rails_learn_journey
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>